### ISSUE TITLE
Conditional Relays

### ISSUE THREAD

**Issue by Cabalist** [kizniche/mycodo_python#1]
Hey @kizniche,

Could you explain what conditional relays are?  

I am specifically looking at this block of code below that was in ```relay_onoff()```.  This is executed after the relay is turned on/off and max amps are checked.

```python
    for i in range(len(conditional_relay_id)):
        if state == 'on':
            if conditional_relay_ifrelay[i] == relay and conditional_relay_ifaction[i] == 'on' and conditional_relay_ifduration[i] == 0:
                if conditional_relay_sel_relay[i]:
                    if conditional_relay_doaction[i] == 'on' and conditional_relay_doduration[i] != 0:
                        rod = threading.Thread(target=relay_on_duration, args=(conditional_relay_dorelay[i], conditional_relay_doduration[i], 0, relay_trigger, relay_pin,))
                        rod.start()
                    else:
                        relay_onoff(conditional_relay_dorelay[i], conditional_relay_doaction[i])
                if conditional_relay_sel_command[i]:
                    p = subprocess.Popen(conditional_relay_do_command[i], shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                    output, errors = p.communicate()
                    logging.debug("[Relay Conditional %s (%s)] Execute command: %s Command output: %s Command errors: %s", i, conditional_relay_name[i], conditional_relay_do_command[i], output, errors)
                if conditional_relay_sel_notify[i] and conditional_relay_time_notify[i] < time.time():
                    logging.debug("[Relay Conditional %s (%s)] True: Notify %s", i, conditional_relay_name[i], conditional_relay_do_notify[i])
                    if conditional_relay_doaction[i] == 'on' and conditional_relay_doduration[i] != 0:
                        message = "Relay Conditional %s (%s): Relay %s turned %s for %s seconds." % ((i), conditional_relay_name[i], relay, conditional_relay_doaction[i], conditional_relay_doduration[i])
                    else:
                        message = "Relay Conditional %s (%s): Relay %s turned %s." % ((i), conditional_relay_name[i], relay, conditional_relay_doaction[i])
                    email(conditional_relay_do_notify[i], message)
                    conditional_relay_time_notify[i] = time.time() + smtp_wait_time
                elif conditional_relay_sel_notify[i]:
                    logging.debug("[Relay Conditional %s (%s)] True: Waiting to notify %s. %s seconds left to wait to be able to notify again (of %s seconds).", i, conditional_relay_name[i], conditional_relay_do_notify[i], (smtp_wait_time - (smtp_wait_time - (conditional_relay_time_notify[i] - time.time()))), smtp_wait_time)
        elif state == 'off':
            if conditional_relay_ifrelay[i] == relay and conditional_relay_ifaction[i] == 'off':
                if conditional_relay_sel_relay[i]:
                    if conditional_relay_doaction[i] == 'on' and conditional_relay_doduration[i] != 0:
                        rod = threading.Thread(target=relay_on_duration, args=(conditional_relay_dorelay[i], conditional_relay_doduration[i], 0, relay_trigger, relay_pin,))
                        rod.start()
                    else:
                        relay_onoff(conditional_relay_dorelay[i], conditional_relay_doaction[i])
                if conditional_relay_sel_command[i]:
                    p = subprocess.Popen(conditional_relay_do_command[i], shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                    output, errors = p.communicate()
                    logging.debug("[Relay Conditional %s (%s)] Execute command: %s Command output: %s Command errors: %s", i, conditional_relay_name[i], conditional_relay_do_command[i], output, errors)
                if conditional_relay_sel_notify[i] and conditional_relay_time_notify[i] < time.time():
                    if conditional_relay_doaction[i] == 'on' and conditional_relay_doduration[i] != 0:
                        message = "Relay Conditional %s (%s): Relay %s turned %s for %s seconds." % ((i), conditional_relay_name[i], relay, conditional_relay_doaction[i], conditional_relay_doduration[i])
                    else:
                        message = "Relay Conditional %s (%s): Relay %s turned %s." % ((i), conditional_relay_name[i], relay, conditional_relay_doaction[i])
                    email(conditional_relay_do_notify[i], message)
                    conditional_relay_time_notify[i] = time.time() + smtp_wait_time
                elif conditional_relay_sel_notify[i]:
                    logging.debug("[Relay Conditional %s (%s)] True: Waiting to notify %s. %s seconds left to wait to be able to notify again (of %s seconds).", i, conditional_relay_name[i], conditional_relay_do_notify[i], (smtp_wait_time - (smtp_wait_time - (conditional_relay_time_notify[i] - time.time()))), smtp_wait_time)
```

**Comment by kizniche** [comment]
It essentially allows the user to create conditional statements that are able to be executed on a timer (as with sensors) or in a reaction to an event (as with relays).

From the sensor tab:
![mycodo 3 5 92 - fungi kylegabriel com 2015-12-05 16-57-31](https://cloud.githubusercontent.com/assets/838427/11610473/825ce740-9b71-11e5-9fea-e5afe0487a44.png)

**Comment by kizniche** [comment]
It will check if the conditions are true, then execute the selected tasks. I didn't know of a shorter way to write it, so we have these huge nested ifs.

**Comment by kizniche** [comment]
Some examples for relay conditionals:
![mycodo 3 5 92 - 2015-12-05 17-07-25](https://cloud.githubusercontent.com/assets/838427/11610516/c9cecc0a-9b72-11e5-8533-870ff83355e6.png)

**Comment by kizniche** [comment]
I don't know if you've used the web interface, but there's alt/title text for most inputs, that give additional information when the mouse is hovered over it.

Do you want a more detailed explanation of the function, or did my previous comments explain it well enough?

**Comment by Cabalist** [comment]
Gotcha.  OK.   The conditionals are stored in the DB Table RelayConditonal and when a Relay turns on or off that conditional is called.

Could you send me a mycodo.db with some conditionals in it?  I don't have any in mine.

**Comment by Cabalist** [comment]
This is good.  I *REALLY* appreciate you getting back to me so fast.  

I am smashing everything up at the moment.  Glad we are on a second repo.

**Comment by Cabalist** [comment]
These conditionals cascade! 

If I set Relay 1 to turn on when Relay 2 is turned and I set Relay 2 to turn off when Relay 1 is turned on they will just flip flop back and forth.

**Comment by kizniche** [comment]
Yes! Don't configure it illogically! I give a warning under the conditional sections, "Note: Ensure these conditional statements don't produce conflicts with themselves or interfere with running PID controllers."

"With great power comes great responsibility" -Ben Parker

**Comment by Cabalist** [comment]
Exactly!  My first thought was COOL and then HOW DO I BREAK THIS.  haha

**Comment by kizniche** [comment]
Hah. Yeah you can cause some serious damage to your relay or device connected to it. I figured adding even more checks would make this behemoth too big. I anticipated coming back to this some time to figure out how to clean it up so I would be able add more checks.

**Comment by kizniche** [comment]
Maybe just put the checks on the PHP side.

**Comment by Cabalist** [comment]
/me spits on the ground

Maybe.

**Comment by kizniche** [comment]
lol. I kind of expected that.

I'm curious to hear what you think of my mycodo-wrapper.c and suid solution to the update process. I really have no idea if this is a completely horrible idea, but I do know one thing: it works!

**Comment by Cabalist** [comment]
This is an interesting and dangerous part of your code.  It allows a loop state to be created that can damage the hardware and it also allows for arbitrary commands to be run in the shell as root no less!  

This is definitely an admin only level access and even being careful I am fat fingered enough that I would probably fry something.   

I am going to label this as dangerous in the code.  I think the FUNCTIONALITY is a really cool thing but the implementation is probably going to need some security  and sanity checks as it moves forward.

**Comment by kizniche** [comment]
It is where it belongs, the experimental branch. I'd be kind of disappointed if I came here and didn't find something that could burn my house down.

**Comment by Cabalist** [comment]
:heart:
