### ISSUE TITLE
SQL Database Questions

### ISSUE THREAD

**Issue by kizniche** [kizniche/mycodo_python#10]
I've been thinking of how the SQL tables can be improved. I've had the thought to get rid of the separate table for each sensor type and move to a more universal table that can accept all the necessary values that having the tables separate currently grants.

I don't think there's likely to be a sensor that will produce more than 3 unique measurements. That is, what is sensed for the physical hardware. For instance, although temperature, humidity, and dew point can be the end result from a DHT22 sensor, only temperature and humidity is actually measured, while dew point is calculated from the temperature and humidity. This would only occupy measurement1 with temperature settings and measurement2 with humidity settings.

What I'm thinking of when I say universal table, I have in mind something like this:

```
class Sensor(Base):
    __tablename__ = "sensor"
    device_id = Column(TEXT, unique=True, primary_key=True)
    device_name = Column(TEXT)               # ex "inside sensor"
    device_location = Column(TEXT)           # ex "0x27" i2c address (or GPIO)
    device_multiplex = Column(TEXT)          # ex "0x70" multiplexer i2c address (0=not used)
    device_type = Column(TEXT)               # ex "htsensor" type of sensor
    device_measure_period = Column(INT)      # ex "120" seconds between measurements
    device_pre_relay = Column(INT)           # ex "5" relay to activate prior to measure
    device_pre_period = Column(INT)         # ex "20" seconds to run pre_relay
    device_activated = Column(INT)           # ex "1" acquire readings form sensor?
    device_graph = Column(INT)               # ex "1" plot measurements to the graph?
    device_number_measurements = Column(INT) # ex "2" how many sensor measurements?
    yaxis_relay_min = Column(INT)
    yaxis_relay_max = Column(INT)
    yaxis_relay_tics = Column(INT)
    yaxis_relay_mtics = Column(INT)
    measure1_type = Column(TEXT)             # ex "temperature" first sensor measurement
    measure1_yaxis_min = Column(INT)
    measure1_yaxis_max = Column(INT)
    measure1_yaxis_tics = Column(INT)
    measure1_yaxis_mtics = Column(INT)
    measure1_relays_up = Column(TEXT)
    measure1_relays_down = Column(TEXT)
    measure1_relay_high = Column(INT)
    measure1_outmin_high = Column(INT)
    measure1_outmax_high = Column(INT)
    measure1_relay_low = Column(INT)
    measure1_outmin_low = Column(INT)
    measure1_outmax_low = Column(INT)
    measure1_pid_activated = Column(INT)     # ex "1" is the PID activated?
    measure1_pid_setpoint = Column(REAL)     # ex "35" degrees to regulate temperature "up" to
    measure1_pid_direction = Column(TEXT)    # ex "up" direction to regulate? up, down, both
    measure1_pid_period = Column(INT)        # ex "120" seconds between updating PID
    measure1_pid_p = Column(REAL)            # ex "0.5" temperature PID P gain
    measure1_pid_i = Column(REAL)            # ex "0.3" temperature PID I gain
    measure1_pid_d = Column(REAL)            # ex "0.1" temperature PID D gain
    measure2_type = Column(TEXT)             # ex "humidity" second sensor measurement
    measure2_yaxis_min = Column(INT)
    measure2_yaxis_max = Column(INT)
    measure2_yaxis_tics = Column(INT)
    measure2_yaxis_mtics = Column(INT)
    measure2_relays_up = Column(TEXT)
    measure2_relays_down = Column(TEXT)
    measure2_relay_high = Column(INT)
    measure2_outmin_high = Column(INT)
    measure2_outmax_high = Column(INT)
    measure2_relay_low = Column(INT)
    measure2_outmin_low = Column(INT)
    measure2_outmax_low = Column(INT)
    measure2_pid_activated = Column(INT)
    measure2_pid_setpoint = Column(REAL)
    measure2_pid_direction = Column(TEXT)
    measure2_pid_period = Column(INT)
    measure2_pid_p = Column(REAL)
    measure2_pid_i = Column(REAL)
    measure2_pid_d = Column(REAL)
    measure3_type = Column(TEXT)             # if only 2 measurements, the following not used
    measure3_yaxis_min = Column(INT)         # ...
    measure3_yaxis_max = Column(INT)
    measure3_yaxis_tics = Column(INT)
    measure3_yaxis_mtics = Column(INT)
    measure3_relays_up = Column(TEXT)
    measure3_relays_down = Column(TEXT)
    measure3_relay_high = Column(INT)
    measure3_outmin_high = Column(INT)
    measure3_outmax_high = Column(INT)
    measure3_relay_low = Column(INT)
    measure3_outmin_low = Column(INT)
    measure3_outmax_low = Column(INT)
    measure3_pid_activted = Column(INT)
    measure3_pid_setpoint = Column(REAL)
    measure3_pid_direction = Column(TEXT)
    measure3_pid_period = Column(INT)
    measure3_pid_p = Column(REAL)
    measure3_pid_i = Column(REAL)
    measure3_pid_d = Column(REAL)
```
Is this a good idea?

How would iterating across measure1_, measure2_, and measure3_ values be best accomplished (Python)?

Thoughts and comments are welcome.

**Comment by zsole2** [comment]
Of course it is a good idea!
As far as I remember the lack of this kind of unified sensor-handling was one of the reason that the graphs could not be rearranged in the stable version. 

Also, I still believe that the sensors and PIDs should be independently handled, I mean that fact that an output relay is controlled by PID has nothing to do with what sensor provided the input for the 
regulation. 

With this new database, one unified table can exist for the sensors, and another one for the PID controllers.

**Comment by kizniche** [comment]
Separation of sensor and PID tables is a great idea. I'll post example tables later, when I get to a computer.

As far as the example sensor table, can you think of a better way of organize it?

Here's an alternate method to the original post example... Measurements are returned in sets (e.g. temperature and humidity), so I if the table were to be set up with an entry for each measurement, there would be two entries for a temp/hum sensor, with the same sensor ID and one with measurement_type "temperature" and the other measurement_type "humidity". This would allow sensing/logging of just one measurement of a multi-condition sensor (not sure of the practicality of that). This would also allow a PID table entry to be match directly with one sensor table entry.

Though, I think what will be the most important factors are: 

Scalability: What if a sensor in the future returns more than 3 unique measurements? The 3-measurement table above will not work.

Ability to reference the entries: Is one table more easily iterable in Python than another? Is one table easier or more efficient to extract the necessary values than another?

**Comment by zsole2** [comment]
Unfortunately I'm not a database expert.
However, I believe that sensor data should be stored as independently as possible. I mean rather than saving sets of data from a sensor (which would couple the data forever), I'd even suggest to generate 'virtual sensors'. So if a sensor provides two (or three or whatever)  types of readings, this sensor should have two (or three) entries in the sensor database table. In that way, all sensor entries would be the same, and the type/ID or any other column would indicate that physically these virtual sensor are linked: The algorithm that stores the readings should be able to handle where to put the data from any given physical sensor device.
With respect of multiple readings provided by one sensor, currently 2 is the max. I don't know how the Sense HAT that was developed for the space mission works, it has several sensors, so in theory, it can provide 5-6 readings... That would be a mess to implement with the original table.

**Comment by kizniche** [comment]
The current state of this new system already has the sensor measurement database (influxdb) entries as distinct measurement types (e.g. "temperature", "humidity", "altitude", etc.). The databases I'm referencing (SQLite) store configurations (sensors, relays, pids, timers, LCDs, UI, SMTP, etc.).

The current system, right now, can handle recording an unlimited number of different measurements from one physical sensor (not 2)... For example, the BMP sensors return temperature, pressure, and altitude. In my original post, I just threw out a potential new sensor table that could bring certain benefits, but its drawback is that it only has 3 "slots" for measurements (for that one physical sensor).

This is the direction I'm now leaning, after a day to chew on this idea.

```
class Sensor(Base):
    __tablename__ = "sensor"
    device_id = Column(TEXT, unique=True, primary_key=True)
    device_name = Column(TEXT)               # ex "inside sensor"
    device_location = Column(TEXT)           # ex "0x27" i2c address (or GPIO)
    device_multiplex = Column(TEXT)          # ex "0x70" multiplexer i2c address (0=not used)
    device_type = Column(TEXT)               # ex "htsensor" type of sensor
    device_measure_period = Column(INT)      # ex "120" seconds between measurements
    device_pre_relay = Column(INT)           # ex "5" relay to activate prior to measure
    device_pre_period = Column(INT)          # ex "20" seconds to run pre_relay
    device_activated = Column(INT)           # ex "1" acquire readings form sensor?
    device_graph = Column(INT)               # ex "1" plot measurements to the graph?
    device_number_measurements = Column(INT) # ex "2" how many sensor measurements?
    measure_type = Column(TEXT)              # ex "temperature" sensor measurement
    measure_unit = Column(TEXT)              # ex "°C"
    measure_clock_pin = Column(INT)          # for use with SHT sensors
    measure_voltage = Column(REAL)           # for use with SHT sensors
    measure_yaxis_min = Column(INT)
    measure_yaxis_max = Column(INT)
    measure_yaxis_tics = Column(INT)
    measure_yaxis_mtics = Column(INT)

class Sensor(Base):
    __tablename__ = "pid"
    sensor_id = Column(TEXT)         # What sensor ID to associate?
    measure_type = Column(TEXT)      # ex "temperature" sensor measurement
    activated = Column(INT)          # ex "1" is the PID activated?
    direction = Column(TEXT)         # ex "up" direction to regulate? up, down, both
    period = Column(INT)             # ex "120" seconds between updating PID
    setpoint = Column(REAL)          # ex "35" degrees desired temperature
    p = Column(REAL)                 # ex "0.5" temperature PID P gain
    i = Column(REAL)                 # ex "0.3" temperature PID I gain
    d = Column(REAL)                 # ex "0.1" temperature PID D gain
    raise_relay = Column(INT)        # relay to raise the condition
    raise_min_duration = Column(INT) # minimum the relay will turn on for
    raise_max_duration = Column(INT) # maximum the relay will turn on for
    lower_relay = Column(INT)        # relay to lower the condition
    lower_min_duration = Column(INT) # minimum the relay will turn on for
    lower_max_duration = Column(INT) # maximum the relay will turn on for

**Comment by kizniche** [comment]
I was able to get the sensor logging and graphing working from just one sensor table, with commit https://github.com/kizniche/mycodo_python/commit/d4eb299dadf5faca63214deef7c81711fddcc44e. It's a slightly modified version of the table above.

**Comment by kizniche** [comment]
So, after chewing on this for a few days, I've come to the conclusion that the new table I created (commit in comment above this) is the best method I can come up with. With this table, the system requires only one entry per sensor to operate.

The new sensor modules located in /mycodo_python/mycodo_core/sensors/ will now handle reading the sensors and building a dictionary of measurement types (e.g. temperature, humidity, co2) as the keys and the measurements as the values. This dictionary will be returned to threaded_sensors.py, for each dictionary entry to be written to influxdb. This allows multiple measurement types to be associated with each sensor, without any limitation to the number of different measurement types that can be entered into the database.

For completeness, what is entered into influxdb is: sensor ID (unique 8-character alpha-numeric), sensor type (e.g. tsensor, htsensor, co2sensor, etc.), sensor measurement (e.g. temperature, humidity, etc.), and the measurement.
