### ISSUE TITLE
time for testing

### ISSUE THREAD

**Issue by zsole2** [kizniche/mycodo_python#15]
Kyle,

Finally I decided to give a spin to this new version. Although I followed the development from the outside, could not find the time (and the PI) to dive into... It looks great from the outside, let's see the details.
Right now, I had a few problems following the setting up instructions:

At the beginning, I got an error message of missing package on my freshly installed Jessie (2016-05-16 version), but a 
     sudo apt-get update
     sudo apt-get upgrade
solved it. 

Next, there is an incorrect version for influxdb in the instructions...no biggie

More serious:
       ~/mycodo_python/init_databases.py -i all
gives error at importing modules, missing mycodo_core. Some places the references were not corrected when you renamed the folders. 
I suggest to use "~" instead of "/home/user" everywhere, it makes it much easier to copy the commands...

HTTP Server:
did not start, although later I realized the I probably forgot to add the symlink 
      'sudo ln -sf /etc/apache2/sites-available/mycodo_flask_apache.conf /etc/apache2/sites-enabled/000-default.conf'
but my error still could be relevant:
at first try, I got access denied for the server, error: "ssl_error_rx_record_too_long". After a quick search, one of the suggestions was to use the command  "a2ensite default-ssl", which I tried and worked.

However, the daemon does not start!!!

'sudo service mycodo status' gives:
pi@chz-3:~ $ sudo service mycodo status
● mycodo.service - Mycodo server
   Loaded: loaded (/home/pi/mycodo_python/mycodo/scripts/mycodo.service; enabled)
   Active: failed (Result: exit-code) since Mon 2016-05-23 20:28:57 CEST; 45min ago
  Process: 3795 ExecStart=/var/www/mycodo/mycodo/mycodo_daemon.py (code=exited, status=1/FAILURE)

May 23 20:28:56 chz-3 mycodo_daemon.py[3795]: File "/var/www/mycodo/mycodo/mycodo_daemon.py", line 38, in <module>
May 23 20:28:56 chz-3 mycodo_daemon.py[3795]: from controller_sensor import SensorController
May 23 20:28:56 chz-3 mycodo_daemon.py[3795]: File "/home/pi/mycodo_python/mycodo/controller_sensor.py", line...ule>
May 23 20:28:56 chz-3 mycodo_daemon.py[3795]: from sensors.am2315 import AM2315_read
May 23 20:28:56 chz-3 mycodo_daemon.py[3795]: File "/home/pi/mycodo_python/mycodo/sensors/am2315.py", line 5,...ule>
May 23 20:28:56 chz-3 mycodo_daemon.py[3795]: from tentacle_pi.AM2315 import AM2315
May 23 20:28:56 chz-3 mycodo_daemon.py[3795]: ImportError: /usr/local/lib/python2.7/dist-packages/tentacle_pi...byte
May 23 20:28:57 chz-3 systemd[1]: mycodo.service: control process exited, code=exited status=1
May 23 20:28:57 chz-3 systemd[1]: Failed to start Mycodo server.
May 23 20:28:57 chz-3 systemd[1]: Unit mycodo.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
pi@chz-3:~ $ 

'sudo ~/mycodo_python/mycodo/mycodo_daemon.py -d' output is:

pi@chz-3:~ $ sudo ~/mycodo_python/mycodo/mycodo_daemon.py -d
Traceback (most recent call last):
  File "/home/pi/mycodo_python/mycodo/mycodo_daemon.py", line 38, in <module>
    from controller_sensor import SensorController
  File "/home/pi/mycodo_python/mycodo/controller_sensor.py", line 20, in <module>
    from sensors.am2315 import AM2315_read
  File "/home/pi/mycodo_python/mycodo/sensors/am2315.py", line 5, in <module>
    from tentacle_pi.AM2315 import AM2315
ImportError: /usr/local/lib/python2.7/dist-packages/tentacle_pi/AM2315.so: undefined symbol: i2c_smbus_write_byte
pi@chz-3:~ $
 
So this is where I am suck at currently, still not bad on the first try. 
Try to continue tomorrow, if yo have any suggestions, please let me know.
Anyway, your huge amount of work seems to coming together nicely!!!

Zsolt

**Comment by kizniche** [comment]
That smbus error is a pain. I managed to fix it by 'sudo purge python-smbus && sudo apt-get install python-smbus'

If that doesn't fix it, I have another command that may solve it.

I'm at work at the moment, but can address your previous comments when I get home.

Thanks!

**Comment by kizniche** [comment]
I updated the readme with the proper influxdb version, added the apt-get update/upgrade commands.

I fixed the init_databases.py issue from the directory restructuring.

Next, a good tip! I had not been using ~ with sudo because I assumed it would refer to /root instead of /home/user. I've gone and replaced all /home/user with ~

The SSL issue should have been resolved with `sudo a2enmod wsgi ssl` however it may be that you didn't restart the daemon with `sudo /etc/init.d/apache2 restart` for that to take effect?

And for the last issue:

```
ImportError: /usr/local/lib/python2.7/dist-packages/tentacle_pi/AM2315.so: undefined symbol: i2c_smbus_write_byte
```

I'm not sure why this happens, but it happened during every install I've tried. I can't figure out if it's either of these two commands (I'll install from scratch again soon):

```sudo purge python-smbus && sudo apt-get install python-smbus```

or

```sudo pip install --upgrade --force-reinstall -r requirements.txt```

**Comment by kizniche** [comment]
I think I figured out the smbus issue. libi2c-dev appears to be required to be installed before tentacle_pi. I've added it to the README, but to get the daemon running, do this:

```sudo apt-get install libi2c-dev```
```sudo pip install -r requirements.txt --upgrade --force-reinstall --no-deps```

**Comment by zsole2** [comment]
Thanks, I can confirm that the daemon starts without error with this fix. No time for further testing until later...

**Comment by zsole2** [comment]
One more thing, the search for the string 'mycodo_core' shows that it occurs also in 'mycodo/scripts/initialize_relays.py'

**Comment by kizniche** [comment]
Good catch, thanks. I should have been more on top of that. I'll push an update later today.
