### ISSUE TITLE
PID settings were not able to be modified: 'bool' object is not callable

### ISSUE THREAD

**Issue by zsole2** [kizniche/mycodo_python#19]
When trying to set up a PID controller, it gave me this error on saving.
It is on a DHT22 sensor, neither temp, nor humidity is working. I also tried different control directions: lower with temp, and both with hum.
I used simply Temperature as measure type, I guess the other types are for different sensor.

Since it was a fresh install, I collected a few other issues, but this is the most important for now.

**Comment by kizniche** [comment]
Ah, there was an "or" missing. Should be fixed with commit 5472291.

**Comment by kizniche** [comment]
What are the other issues?

**Comment by zsole2** [comment]
Thanks for the fix.

Other issues:
-- Cannot add user from the UI, only from command line. Gives the generic internal error message (following your earlier instructions, I could not start flask in daemon mode, it hangs). Deleting user is OK. 
-- Created a log, but download also gives the error

As a feature req, it would be nice to be able to shutdown from the UI.

**Comment by zsole2** [comment]
Quick update... after adding the PID, now my DHT22 sensor is not responding. It may be unrelated, because it's an old one, the CLI test also not working. Investigating a bit...

However, I cannot create graphs now, same internal  error. It used to work, maybe your  commit a few days back moving the graphs  causing it.

**Comment by zsole2** [comment]
OK, the sensor was bad, I had one spare lying around, and it fixed the bad sensor reading. It is still equilibrating, but activated the PID for a short time for testing, and appears to be no problem at all, the old AM2302 died. 
Still no graph after reboot, however...

**Comment by kizniche** [comment]
Thanks for the feedback. The user issue should be fixed with commit 8900874. I'm not sure why you're having problems with the graph or logging (both working fine on my test boards. I can take a look if you give me a login.

**Comment by zsole2** [comment]
I reinstalled Mycodo (again...), and the graphing works, as it worked previously. The only difference as far as I can tell is that the problem is on the Pi Zero, the other one is Pi 3. the Zero has everything set up as I need, all the relays, timers, sensors, the quick test has only the Pi sensors, temp and load. I'll create and send you  login data  in an e-mail later.

**Comment by kizniche** [comment]
Thanks. If you can give me ssh access (wish sudo?) and Mycodo access, that would be most helpful.

**Comment by zsole2** [comment]
I created the mycodo account for you, but after this I realized that my system is only accessible to the outside world by VPN, and I will have to refresh how I set up everything long time agoto do it again...
Then I arrived home, and something else happened which made me want to rebuild the whole system to check everything again. Maybe Wednesday I will have time for it. I'll check back with more data.
